# Generated by Django 3.0.3 on 2020-04-03 19:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbtcat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CbtcatUsers',
            new_name='CbtcatUser',
        ),
        migrations.RenameModel(
            old_name='Lvl1Answers',
            new_name='Lvl1Answer',
        ),
        migrations.RenameModel(
            old_name='Lvl5Answers',
            new_name='Lvl2Answer',
        ),
        migrations.RenameModel(
            old_name='Lvl4Answers',
            new_name='Lvl3Answer',
        ),
        migrations.RenameModel(
            old_name='Lvl2Answers',
            new_name='Lvl4Answer',
        ),
        migrations.RenameModel(
            old_name='Lvl3Answers',
            new_name='Lvl5Answer',
        ),
        migrations.RenameModel(
            old_name='Lvl6Answers',
            new_name='Lvl6Answer',
        ),
    ]
