# Generated by Django 3.0.3 on 2020-04-04 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbtcat', '0005_auto_20200403_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbtcatuser',
            name='lvl_1',
        ),
        migrations.RemoveField(
            model_name='cbtcatuser',
            name='lvl_2',
        ),
        migrations.RemoveField(
            model_name='cbtcatuser',
            name='lvl_3',
        ),
        migrations.RemoveField(
            model_name='cbtcatuser',
            name='lvl_4',
        ),
        migrations.RemoveField(
            model_name='cbtcatuser',
            name='lvl_5',
        ),
        migrations.RemoveField(
            model_name='cbtcatuser',
            name='lvl_6',
        ),
        migrations.AddField(
            model_name='cbtcatuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lvl1answer',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AddField(
            model_name='lvl2answer',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AddField(
            model_name='lvl3answer',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AddField(
            model_name='lvl4answer',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AddField(
            model_name='lvl5answer',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AddField(
            model_name='lvl6answer',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AlterField(
            model_name='cbtcatuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
