# Generated by Django 3.0.3 on 2020-04-04 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbtcat', '0006_auto_20200404_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lvl1answer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='lvl2answer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='lvl3answer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='lvl4answer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='lvl5answer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='lvl6answer',
            name='username',
        ),
        migrations.AddField(
            model_name='lvl1answer',
            name='cbtcat_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AddField(
            model_name='lvl2answer',
            name='cbtcat_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AddField(
            model_name='lvl3answer',
            name='cbtcat_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AddField(
            model_name='lvl4answer',
            name='cbtcat_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AddField(
            model_name='lvl5answer',
            name='cbtcat_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AddField(
            model_name='lvl6answer',
            name='cbtcat_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser'),
        ),
        migrations.AlterField(
            model_name='cbtcatuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
