# Generated by Django 3.0.3 on 2020-05-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0012_auto_20200406_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lvl1UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_unique_users_started', models.IntegerField(default=0)),
                ('num_unique_users_completed', models.IntegerField(default=0)),
                ('total_times_started', models.IntegerField(default=0)),
                ('total_times_finished', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cbtcatuser',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('cbtcat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbtcat.CbtcatUser')),
            ],
        ),
    ]
