# Generated by Django 3.0.3 on 2020-05-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0013_auto_20200505_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvl1answer',
            name='current_question',
            field=models.IntegerField(default=1),
        ),
    ]
