# Generated by Django 3.0.3 on 2020-05-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0015_lvl1answer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lvl1answer',
            old_name='cbtcat_user',
            new_name='cbtcat_user_id',
        ),
    ]
