# Generated by Django 3.0.3 on 2020-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0017_auto_20200507_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='L1A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('current_question', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
