# Generated by Django 3.0.3 on 2020-05-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0019_auto_20200507_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lvl1Answer',
        ),
    ]
