# Generated by Django 3.0.3 on 2020-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0020_delete_lvl1answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='L2Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('finished_on', models.DateTimeField(auto_now=True, null=True)),
                ('current_question', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='L3Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('finished_on', models.DateTimeField(auto_now=True, null=True)),
                ('current_question', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='L4Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('finished_on', models.DateTimeField(auto_now=True, null=True)),
                ('current_question', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='L5Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('finished_on', models.DateTimeField(auto_now=True, null=True)),
                ('current_question', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='L6Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('finished_on', models.DateTimeField(auto_now=True, null=True)),
                ('current_question', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
