# Generated by Django 3.0.3 on 2020-05-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0021_l2ans_l3ans_l4ans_l5ans_l6ans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lvl2Answer',
        ),
        migrations.DeleteModel(
            name='Lvl3Answer',
        ),
        migrations.DeleteModel(
            name='Lvl4Answer',
        ),
        migrations.DeleteModel(
            name='Lvl5Answer',
        ),
        migrations.DeleteModel(
            name='Lvl6Answer',
        ),
    ]
