# Generated by Django 3.0.3 on 2020-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0023_lvl2userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvl1userdata',
            name='table_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lvl2userdata',
            name='table_created',
            field=models.BooleanField(default=True),
        ),
    ]
