# Generated by Django 3.0.3 on 2020-05-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0024_auto_20200508_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lvl3UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_created', models.BooleanField(default=True)),
                ('num_unique_users_started', models.IntegerField(default=0)),
                ('num_unique_users_completed', models.IntegerField(default=0)),
                ('total_times_started', models.IntegerField(default=0)),
                ('total_times_finished', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lvl4UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_created', models.BooleanField(default=True)),
                ('num_unique_users_started', models.IntegerField(default=0)),
                ('num_unique_users_completed', models.IntegerField(default=0)),
                ('total_times_started', models.IntegerField(default=0)),
                ('total_times_finished', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lvl5UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_created', models.BooleanField(default=True)),
                ('num_unique_users_started', models.IntegerField(default=0)),
                ('num_unique_users_completed', models.IntegerField(default=0)),
                ('total_times_started', models.IntegerField(default=0)),
                ('total_times_finished', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lvl6UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_created', models.BooleanField(default=True)),
                ('num_unique_users_started', models.IntegerField(default=0)),
                ('num_unique_users_completed', models.IntegerField(default=0)),
                ('total_times_started', models.IntegerField(default=0)),
                ('total_times_finished', models.IntegerField(default=0)),
            ],
        ),
    ]
