# Generated by Django 3.0.3 on 2020-05-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0025_lvl3userdata_lvl4userdata_lvl5userdata_lvl6userdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='l1a',
            options={'ordering': ['username', 'created_on']},
        ),
        migrations.AlterModelOptions(
            name='l2ans',
            options={'ordering': ['username', 'created_on']},
        ),
        migrations.AlterModelOptions(
            name='l3ans',
            options={'ordering': ['username', 'created_on']},
        ),
        migrations.AlterModelOptions(
            name='l4ans',
            options={'ordering': ['username', 'created_on']},
        ),
        migrations.AlterModelOptions(
            name='l5ans',
            options={'ordering': ['username', 'created_on']},
        ),
        migrations.AlterModelOptions(
            name='l6ans',
            options={'ordering': ['username', 'created_on']},
        ),
        migrations.AlterModelOptions(
            name='login',
            options={'ordering': ['username']},
        ),
        migrations.RemoveField(
            model_name='login',
            name='cbtcat_user',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
