# Generated by Django 3.0.3 on 2020-05-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtcat', '0026_auto_20200514_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='date',
        ),
        migrations.RemoveField(
            model_name='login',
            name='time',
        ),
        migrations.AddField(
            model_name='login',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
